/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * flash.java
 *
 * Created on 18 Ιουν 2010, 1:47:58 μμ
 */
package com.googlecode.flashgamesplayer.games;

import chrriis.dj.nativeswing.swtimpl.components.JFlashPlayer;
import java.awt.BorderLayout;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import com.googlecode.flashgamesplayer.FlashGamesPlayer;
import com.googlecode.flashgamesplayer.database.Game;
import com.googlecode.flashgamesplayer.tools.GamesChangeListener;
import com.googlecode.flashgamesplayer.tools.MyFunctions;
import com.googlecode.flashgamesplayer.tools.Options;

/**
 *
 * @author ssoldatos
 */
public class GamePanel extends javax.swing.JPanel {

  private JFlashPlayer flashPlayer;
  private Game game;

  /** Creates new form flash */
  public GamePanel() {
    super(new BorderLayout());
  }

  public void setGame(Game game) {
    if (flashPlayer != null) {
      remove(flashPlayer);
    }
    flashPlayer = new JFlashPlayer();
    flashPlayer.load(Options.USER_DIR + Options.GAMES_DIR + game.getFilename());
    add(flashPlayer, BorderLayout.CENTER);
    validate();
    this.game = game;
    try {
      Game.updatePlayed(game.getId());
    } catch (SQLException ex) {
      FlashGamesPlayer.logger.log(Level.SEVERE, null, ex);
    }
  }

  public Game getGame() {
    return game;
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    setLayout(new java.awt.BorderLayout());
  }// </editor-fold>//GEN-END:initComponents
  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables
}
