/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * flash.java
 *
 * Created on 18 Ιουν 2010, 1:47:58 μμ
 */
package com.googlecode.flashgamesplayer.games;

import chrriis.dj.nativeswing.swtimpl.components.JFlashPlayer;
import java.awt.BorderLayout;
import java.sql.SQLException;
import java.util.logging.Level;
import com.googlecode.flashgamesplayer.FlashGamesPlayer;
import com.googlecode.flashgamesplayer.database.Game;
import com.googlecode.flashgamesplayer.database.Genre;
import com.googlecode.flashgamesplayer.database.Options;

/**
 *
 * @author ssoldatos
 */
public class GamePanel extends javax.swing.JPanel {

  private JFlashPlayer flashPlayer;
  private Game game;
  private int genre_id;

  /** Creates new form flash */
  public GamePanel() {
    super(new BorderLayout());
  }

  public void setGame(Game game) {
    setGame(game,true);
  }

  public void setGame(Game game, boolean play) {
    if (game == null) {
      this.game = new Game();
    } else {
      this.game = Game.getGameById(game.getId());
    }
    if (getFlashPlayer() != null) {
      remove(getFlashPlayer());
    }
    flashPlayer = new JFlashPlayer();
    try {
      if (game != null && game.getDeleted() == 0 && play) {
        getFlashPlayer().load(Options.USER_DIR + Options.GAMES_DIR + game.getFilename());
        game.setPlayed(this.game.getId());
      }
    } catch (Exception ex) {
    }
    add(getFlashPlayer(), BorderLayout.CENTER);
    validate();
    //this.genre_id = this.game.getGenre_id();
    FlashGamesPlayer.label_gameTitle.setText(this.game.getTitle());
    FlashGamesPlayer.rating.setRate(this.game.getRate());
    FlashGamesPlayer.rating.setRatingEnabled(true);
    FlashGamesPlayer.tf_plays.setText(String.valueOf(this.game.getPlayed()));
    FlashGamesPlayer.bt_savePassword.setEnabled(game != null);
    FlashGamesPlayer.tf_password.setText(this.game.getPassword());
    FlashGamesPlayer.bt_delete.setEnabled(game != null && game.getDeleted() == 0);
    FlashGamesPlayer.menuItem_deleteGame.setEnabled(game != null && game.getDeleted() == 0);
    FlashGamesPlayer.bt_restore.setEnabled(game != null && game.getDeleted() == 1);

  }

  public Game getGame() {
    return game;
  }

  public Genre getGenre() {
    return Genre.getGenreById(this.genre_id);
  }

  public JFlashPlayer getFlashPlayer() {
    return this.flashPlayer;
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    setLayout(new java.awt.BorderLayout());
  }// </editor-fold>//GEN-END:initComponents
  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables
}
