/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GenresForm.java
 *
 * Created on 25 Ιουλ 2010, 5:56:10 μμ
 */
package com.googlecode.flashgamesplayer.genres;

import com.googlecode.flashgamesplayer.FlashGamesPlayer;
import com.googlecode.flashgamesplayer.database.Genre;
import com.googlecode.flashgamesplayer.tools.MyDraggable;
import java.sql.SQLException;
import java.util.Iterator;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ssoldatos
 */
public class GenresForm extends MyDraggable {

  private static final long serialVersionUID = 7678687678L;
   DefaultTableModel model  = new GenreTableModel();

  /** Creates new form GenresForm */
  public GenresForm() {
    initComponents();
    populateTable();
    table.getColumnModel().getColumn(0).setMaxWidth(550);
    table.getColumnModel().getColumn(0).setHeaderValue("Genre");
    table.getColumnModel().getColumn(1).setMaxWidth(80);
    table.getColumnModel().getColumn(1).setHeaderValue("Delete");
    table.getColumnModel().getColumn(1).setCellRenderer(new EditGenreRenderer());
    table.getColumnModel().getColumn(0).setCellRenderer(new GenreRenderer());
    table.setRowHeight(26);
    model.addTableModelListener(new GenreTableModelListener(this));
    setLocationRelativeTo(null);
    table.addMouseListener(new GenreTableMouseListener(this));
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    scrollpane = new javax.swing.JScrollPane();
    table = new javax.swing.JTable();
    bt_add = new javax.swing.JButton();
    bt_close = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

    jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

    jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD, jLabel1.getFont().getSize()+2));
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Edit Games Genres");

    table.setModel(model);
    scrollpane.setViewportView(table);

    bt_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/googlecode/flashgamesplayer/images/addGame.png"))); // NOI18N
    bt_add.setToolTipText("Add a new Genre");
    bt_add.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        bt_addActionPerformed(evt);
      }
    });

    bt_close.setText("Close");
    bt_close.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        bt_closeActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(scrollpane, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
          .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
          .addComponent(bt_add)
          .addComponent(bt_close))
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addGap(12, 12, 12)
        .addComponent(bt_add)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(scrollpane, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(bt_close)
        .addContainerGap(12, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void bt_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_closeActionPerformed
      dispose();
    }//GEN-LAST:event_bt_closeActionPerformed

    private void bt_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_addActionPerformed
      Object type = JOptionPane.showInputDialog(null, "Genre :", "Add genre", JOptionPane.QUESTION_MESSAGE);
      String g = (String) type;
      Genre genre = new Genre();
      genre.setGenre(g);
    try {
      genre.save();
      populateTable();
    } catch (SQLException ex) {
      FlashGamesPlayer.logger.log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_bt_addActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {

      public void run() {
        new GenresForm().setVisible(true);
      }
    });
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton bt_add;
  private javax.swing.JButton bt_close;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane scrollpane;
  private javax.swing.JTable table;
  // End of variables declaration//GEN-END:variables

  public void populateTable() {
    model.setRowCount(0);
    Vector<Genre> genres = Genre.getAll();
    for (Iterator<Genre> it = genres.iterator(); it.hasNext();) {
      Genre genre = it.next();
      Object[] data = {genre,genre};
      model.addRow(data);
    }
    //table.setModel(model);
  }
}
